Accept exception_handlers as Mapping
Kludex/starlette pull request #1139
Opened 2021-02-08 19:55 UTC by antonagestam

This change does two things: the first is that it communicates to the caller that the passed dict isn't going to be mutated. The second is that it allows the caller to pass any Mapping without first casting it to a dict, which is very redundant since that already happens inside `__init__`.

2021-02-08 20:00 UTC, Kludex commented
![image](https://user-images.githubusercontent.com/7353520/107274414-a13d2900-6a50-11eb-862b-3d5ffa41521f.png)

2021-04-12 20:58 UTC, JayH5 commented
I do think `Mapping` is the right type here, but the fact that the key type is a `Union` of two types means that #1142 is still an issue. Mappings and dicts are not covariant in their key types, so really the best we can do is `Mapping[Any, Callable]`

2021-12-13 13:53 UTC, aminalaee commented
@antonagestam Will you update this?

2021-12-13 13:53 UTC, aminalaee requested changes

2021-12-13 13:53 UTC, aminalaee commented on starlette/applications.py
>          ] = None,
```suggestion
        exception_handlers: typing.Mapping[typing.Any typing.Callable] = None,
```

2021-12-15 11:20 UTC, antonagestam commented
I'll try to get to addressing this soon.

2021-12-17 23:08 UTC, antonagestam commented
Updated to use a contravariant typevar, which makes this also close #1142.

2022-01-30 15:27 UTC, Kludex commented
This was closed by #1360.

Thanks for the PR @antonagestam ! :)

2022-01-30 15:39 UTC, antonagestam commented
@Kludex Oh, note that I updated this PR to solve the problem without introducing `Any` for the key type, so I still think there's value in integrating some of that work.

2022-01-30 15:41 UTC, Kludex commented
Cool! I've opened again! :)

2022-01-30 16:34 UTC, antonagestam commented
@Kludex I opened #1456 to supersede this one.

2022-01-30 16:34 UTC, closed without merging