Allow for custom head method in HTTPEndpoint
Kludex/starlette pull request #1222
Opened 2021-06-27 18:34 UTC by theblazehen

Fix for https://github.com/encode/starlette/issues/1221

2021-06-28 08:16 UTC, theblazehen commented on starlette/endpoints.py
> +                handler_name = "head"
No. In which file would the relevant tests be?

2021-06-28 08:24 UTC, aminalaee commented on starlette/endpoints.py
> +                handler_name = "head"
Not really sure, maybe `tests/test_endpoints.py`. Or any other places using `HTTPEndpoint`

2021-06-28 09:32 UTC, aminalaee commented on starlette/endpoints.py
> +        if request.method == "HEAD":
It's safer to check `request.method.lower() == "head"`

2021-09-25 21:49 UTC, Kludex commented on starlette/endpoints.py
> +
```suggestion
        method = request.method.lower()
        handler_name = "get" if method == "head" and not hasattr(self, "head") else method
```

2021-09-25 21:51 UTC, Kludex requested changes
@theblazehen Thanks for the PR! 🎉 

Can you rebase it and check my comment?

2021-09-25 21:51 UTC, Kludex commented on starlette/endpoints.py
> +
```suggestion
```suggestion
        method = request.method.lower()
        handler_name = (
            "get" if method == "head" and not hasattr(self, "head") else method
        )
```
```

2021-11-23 10:09 UTC, Kludex commented
@theblazehen Do you wish to resume your work? Otherwise, I'll be closing as stale :kissing:

2021-11-27 16:17 UTC, Kludex commented
Close in favor of #1346

2021-11-27 16:17 UTC, closed without merging