Add starsessions library to the 3rd-party list.
Kludex/starlette pull request #1225
Opened 2021-06-28 16:16 UTC by alex-oleshkevich

This PR adds [starsessions](https://github.com/alex-oleshkevich/starsessions) library to the list of Starlette plugins.

Relates to https://github.com/encode/starlette/pull/499

2021-09-16 17:54 UTC, Kludex requested changes
Thanks for the PR @alex-oleshkevich ! :tada: 

Would you mind rebasing it?

2021-09-16 17:54 UTC, Kludex commented on docs/third-party-packages.md
> +An alternate session support implementation. With customizable storage backends.
```suggestion
An alternate session support implementation with customizable storage backends.
```

2021-09-22 08:30 UTC, alex-oleshkevich commented
Updated.

2021-09-22 08:35 UTC, Kludex approved these changes
Thanks @alex-oleshkevich ! :tada:

2021-09-22 08:35 UTC, merged