Use zero copy to send file if can
Kludex/starlette pull request #1288
Opened 2021-09-22 01:26 UTC by abersheeran

https://asgi.readthedocs.io/en/latest/extensions.html#zero-copy-send

2021-10-10 14:47 UTC, Kludex requested changes

2021-10-10 14:47 UTC, Kludex commented on starlette/responses.py
> +                os.close(fd)
```suggestion
                await anyio.to_thread.run_sync(os.close, fd)
```

2021-10-10 14:47 UTC, Kludex commented on starlette/responses.py
> +            fd = os.open(self.path, open_mode)
```suggestion
            fd = await anyio.to_thread.run_sync(os.open, self.path, open_mode)
```

2021-10-10 14:48 UTC, Kludex commented on starlette/responses.py
> +        elif "http.response.zerocopysend" in scope["extensions"]:  # pragma: no cover
Why should we not test it?

2021-10-10 14:58 UTC, synodriver commented
By the way, should we use [range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) and [if-range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Range) header?

2021-10-10 15:10 UTC, abersheeran commented on starlette/responses.py
> +        elif "http.response.zerocopysend" in scope["extensions"]:  # pragma: no cover
I'm not sure how to test it. It seems too simple to just test if the result it returns is a dictionary. Do you have any suggestions?

2021-10-10 15:11 UTC, abersheeran commented
> By the way, should we use [range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) and [if-range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Range) header? I saw it in [someones toolkit](https://github.com/abersheeran/baize/blob/5e84d69c2389aa46c81e5f4e96de54db4f0f1d3b/baize/asgi.py#L630-L640)

https://github.com/encode/starlette/pull/1013

2021-10-10 15:19 UTC, synodriver commented
> > By the way, should we use [range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) and [if-range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Range) header? I saw it in [someones toolkit](https://github.com/abersheeran/baize/blob/5e84d69c2389aa46c81e5f4e96de54db4f0f1d3b/baize/asgi.py#L630-L640)
> 
> #1013

Than you for pointing out. But is that means ```zerocopysend``` have to do something in order to implement that? Like adding ```offset``` and ```count``` params.

2021-10-10 15:20 UTC, abersheeran commented
In addition, `baize.asgi.FileResponse` can work with Starlette. Just try the following code

```python
# main.py
from starlette.applications import Starlette
from starlette.routing import Route
from baize.asgi import FileResponse


async def homepage(request):
    return FileResponse("./main.py")

routes = [
    Route("/", endpoint=homepage)
]

app = Starlette(debug=True, routes=routes)
```

2021-10-10 15:21 UTC, abersheeran commented
> > > By the way, should we use [range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) and [if-range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Range) header? I saw it in [someones toolkit](https://github.com/abersheeran/baize/blob/5e84d69c2389aa46c81e5f4e96de54db4f0f1d3b/baize/asgi.py#L630-L640)
> > 
> > 
> > #1013
> 
> Than you for pointing out. But is that means `zerocopysend` have to do something in order to implement that? Like adding `offset` and `count` params.

Yes. These parameters need to be specified.

2021-10-10 15:21 UTC, synodriver commented
> In addition, `baize.asgi.FileResponse` can work with Starlette. Just try the following code
> 
> ```python
> # main.py
> from starlette.applications import Starlette
> from starlette.routing import Route
> from baize.asgi import FileResponse
> 
> 
> async def homepage(request):
>     return FileResponse("./main.py")
> 
> routes = [
>     Route("/", endpoint=homepage)
> ]
> 
> app = Starlette(debug=True, routes=routes)
> ```

Great feature!

2021-10-10 15:24 UTC, abersheeran commented
> > In addition, `baize.asgi.FileResponse` can work with Starlette. Just try the following code
> > ```python
> > # main.py
> > from starlette.applications import Starlette
> > from starlette.routing import Route
> > from baize.asgi import FileResponse
> > 
> > 
> > async def homepage(request):
> >     return FileResponse("./main.py")
> > 
> > routes = [
> >     Route("/", endpoint=homepage)
> > ]
> > 
> > app = Starlette(debug=True, routes=routes)
> > ```
> 
> Great feature!

Simply because they support the ASGI3 protocol. I was fascinated by this design in Starlette, so I implemented a similar part for WSGI.

2021-10-10 15:33 UTC, synodriver approved these changes

2022-02-11 10:57 UTC, tomchristie commented on starlette/responses.py
> +                await anyio.to_thread.run_sync(os.close, fd)
I'm... not comfortable with this.
Not at all obvious to me how the open/zerocopesend/close would interact.

I've got a bit of a preference here that we close this off for now as a "feature pause" until we're sufficiently on top of all existing issues that we can *thoroughly* review this.

2022-02-11 13:00 UTC, closed without merging