Add proper type hints to add_exception_handler
Kludex/starlette pull request #1308
Opened 2021-10-11 22:01 UTC by phillipuniverse

I lost a bit of time due to a missing return statement and type hint in an exception handler. 

In my case I had registered an `HTTPException` exception handler without a return. Here's the exception I ended up with:

```
Traceback (most recent call last):
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/myproj-0dUE00O2-py3.8/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/myproj-0dUE00O2-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 609, in __call__
    await self.default(scope, receive, send)
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/myproj-0dUE00O2-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 497, in not_found
    raise HTTPException(status_code=404)
starlette.exceptions.HTTPException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/myproj-0dUE00O2-py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/myproj-0dUE00O2-py3.8/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/myproj-0dUE00O2-py3.8/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    await response(scope, receive, sender)
TypeError: 'NoneType' object is not callable
```

Here's what my exception handler and registration looked like:

```python
...

async def http_exception_handler(request, exc):
   JSONResponse(
        status_code=exc.status_code,
        content=jsonable_encoder(
            {
                "errors": [
                    {
                        "id": uuid4(),
                        "title": "Internal Exception",
                        "detail": exc.detail,
                    }
                ]
            }
        ),
    )

application.add_exception_handler(HTTPException, http_exception_handler)
```

This is clearly an error but it would've been nice to get a type hint error on it before I went through and traced down the implementation.

Thanks for such a great library!

2021-10-12 13:42 UTC, phillipuniverse commented
I realized there are a lot of other callables in the `Starlette` application that are not correctly type hinted. I can expand this PR to type hint the rest of those if that is desirable.

2021-11-15 20:15 UTC, Kludex requested changes
Yeah, PRs improving the type hints are welcome.

As for this PR, can we also add the type hint on the `starlette/exceptions.py` file as well (in the analogous signature)?

2021-11-15 20:15 UTC, Kludex commented on starlette/applications.py
> +        handler: typing.Callable[[Request, Exception], typing.Union[Response, typing.Coroutine[typing.Any, typing.Any, Response]]],
Should we perhaps use `Awaitable` instead? It looks better. :kissing: 

```suggestion
        handler: typing.Callable[[Request, Exception], typing.Union[Response, Awaitable[Response]]],
```

2022-01-26 09:23 UTC, aminalaee commented
@phillipuniverse Are you willing to address the changes requested?

2022-01-28 03:04 UTC, phillipuniverse commented
@aminalaee yes! Sorry, this fell off my radar a bit. I’ll get this back on track in the next couple of days.

2022-02-01 16:10 UTC, Kludex commented
Thanks for the PR @phillipuniverse !

There's a discussion on #1456 about the idea we see here, so I'll close this PR.

2022-02-01 16:10 UTC, closed without merging