Add authentication requires args length check
Kludex/starlette pull request #1335
Opened 2021-11-10 13:47 UTC by LarsStegman

Fix for `IndexError` when both `args` and `kwargs` are specified, resulting in the possibility of trying to access a tuple index that is higher than the tuple size.

Solves #1334

2021-11-15 12:59 UTC, LarsStegman commented
Did someone get a chance to take a look at this and run the workflows?

2021-11-15 19:26 UTC, Kludex commented
> Did someone get a chance to take a look at this and run the workflows?

Yes, but this approach looks more as a workaround. I've developed an alternative solution on #1337, which I'm unsure if we should merge it.

2021-11-15 21:39 UTC, Kludex requested changes
I'm willing to accept it now. Just a linter issue :)

2021-11-15 21:39 UTC, Kludex commented on starlette/authentication.py
> +                )
```suggestion
                websocket = kwargs.get("websocket", args[idx] if idx < len(args) else None)
```

2021-11-15 21:39 UTC, Kludex commented on starlette/authentication.py
> +                )
```suggestion
                request = kwargs.get("request", args[idx] if idx < len(args) else None)
```

2021-11-15 21:39 UTC, Kludex commented on starlette/authentication.py
> +                )
```suggestion
                request = kwargs.get("request", args[idx] if idx < len(args) else None)
```

2021-11-15 21:43 UTC, LarsStegman commented
Yes, I shouldn't try to fix it in the browser with no linting help haha. Thanks!

2021-11-15 21:45 UTC, Kludex commented on starlette/authentication.py
> +                websocket = kwargs.get("websocket", args[idx] if idx < len(args) else None)
This one was alright... Sorry 😅

2021-11-15 21:53 UTC, Kludex approved these changes
Thanks @LarsStegman ! 🎉

2021-11-15 21:54 UTC, merged

2021-11-16 07:13 UTC, LarsStegman commented
Could this fix be released in a new minor version so we can change our dependencies?