Do not read file for HEAD method on StaticFiles
Kludex/starlette pull request #176
Opened 2018-11-02 14:21 UTC by laixintao

Hi, I am try to resolve https://github.com/encode/starlette/issues/45 problem2.

Don't know if I'm doing it in the right way. Hope you can give me some feedback.

I mocked `aiofiles.open` in testcase to ensure that we don't read files.

2018-11-05 11:48 UTC, lovelydinosaur requested changes

2018-11-05 13:48 UTC, laixintao commented on starlette/responses.py
> +            await send({"type": "http.disconnect"})
Hi, thanks for you review :) I updated as you said, but can you give more details about why send empty body instead of `disconnect`?  Thanks.

2018-11-08 16:05 UTC, laixintao commented
@tomchristie Can it be merged?

2018-11-08 16:40 UTC, lovelydinosaur requested changes

2018-11-08 16:40 UTC, tomchristie commented on starlette/responses.py
> +        send_header_only: bool = False,
Let's use `method: str = None` here. It'll be marginally nicer if the developer can just do `method=request.method`.

2018-11-08 16:40 UTC, tomchristie commented on starlette/responses.py
> +        self.send_header_only = send_header_only
Then we can do `self.send_header_only = method is not None and method.upper() == "HEAD"`

2018-11-08 16:41 UTC, tomchristie commented on starlette/staticfiles.py
> +                    send_header_only=send_header_only,
This will be `method=self.scope["method"]`

2018-11-08 16:42 UTC, tomchristie commented
@laixintao - Looks great, thank you! I've made one minor request to tweak the API.
After that yup, let's get this in. ✨

2018-11-08 16:57 UTC, tomchristie commented on starlette/staticfiles.py
> +                request = Request(self.scope, receive)
In this *particular* case don't bother to instantiate a request instance.
Just use `method = self.scope["method"]`.

2018-11-08 16:58 UTC, lovelydinosaur approved these changes

2018-11-08 16:58 UTC, tomchristie commented
Very cool. Thanks!

2018-11-08 16:59 UTC, merged

2018-11-08 17:01 UTC, tomchristie commented
Released as 0.8.2 👍