Test client init to support headers argument
Kludex/starlette pull request #1966
Opened 2022-11-28 21:45 UTC by roy-pstr

The starting point for contributions should usually be [a discussion](https://github.com/encode/starlette/discussions)

Simple documentation typos may be raised as stand-alone pull requests, but otherwise please ensure you've discussed your proposal prior to issuing a pull request.

This will help us direct work appropriately, and ensure that any suggested changes have been okayed by the maintainers.

- [ ] Initially raised as discussion #...

2022-11-29 00:03 UTC, danielballan commented on starlette/testclient.py
> +        if "user-agent" not in headers:
This might be a good place to use `headers.setdefault("user-agent", "testclient")`.

2022-12-02 08:55 UTC, Kludex requested changes

2022-12-02 08:55 UTC, Kludex commented on starlette/testclient.py
> +        )  # for backwards compatibility in case no user-agent is set
```suggestion
        headers.setdefault("user-agent", "testclient")
```

2022-12-02 08:55 UTC, Kludex commented on tests/test_testclient.py
> +    This could useful if we need to set custom headers for authentication
```suggestion
    This is useful if we need to set custom headers for authentication
```

2022-12-02 08:55 UTC, Kludex commented on tests/test_testclient.py
> +    make sure default value of "user-agent" is "testclient" unless overridden.
```suggestion
```

2022-12-03 06:41 UTC, Kludex approved these changes

2022-12-03 06:41 UTC, Kludex commented
Thanks @roy-pstr ! :)

2022-12-03 07:39 UTC, Kludex commented
Just for record keeping...

Even though it's possible to add the headers to the `TestClient` after the client is instantiated, it's more comfortable to add the headers' parameter. It's not only about practicality, but I believe people will make a good use of this feature.

Also, do not take this PR as an argument to add the other parameters supported by `httpx` client.

2022-12-03 07:40 UTC, merged