Add env argument to Jinja2Templates, remove **env_options. (ref #2134)
Kludex/starlette pull request #2159
Opened 2023-05-31 10:35 UTC by alex-oleshkevich

This PR adds `env` argument to `Jinja2Templates` class and removes `**env_options`. 

**Motivation**
See this discussion - #2134

1. arguments of `Jinja2Templates` configure only this class and nothing else
2. users can configure `jinja2.Environment` and use it in the app without limits
3. the `Environment` class may be used by other app components, not just by Starlette

This is a  breaking change!

**Example**
```python
import jinja2
from starlette.templating import Jinja2Templates

env = jinja2.Environment(...)
templates = Jinja2Templates(env=env)
```

2023-05-31 12:30 UTC, NickColley commented
I like this, it meets the "starlette has a simple opinionated way" need whilst also allowing the user to do something really complicated without the starlette project having to think about a new API at all - since it falls to a shared idea of the Jinja environment which is referenced and used in many different jinja projects.

2023-05-31 15:51 UTC, Kludex commented
Can we deprecate the `**env_options` first, then remove it on v1?

2023-06-01 10:03 UTC, Kludex commented on starlette/templating.py
>      def __init__(
Can we overload this?

2023-06-01 10:11 UTC, alex-oleshkevich commented on starlette/templating.py
>      def __init__(
good idea

2023-06-01 18:09 UTC, Kludex requested changes
With the overload and the rebase, we are done here 👍

2023-06-01 18:09 UTC, Kludex commented on starlette/templating.py
> +        **env_options: typing.Any,
```suggestion
        self, directory: typing.Union[str, PathLike], **env_options: typing.Any
```

2023-06-01 18:09 UTC, Kludex commented on tests/test_templates.py
> +def test_templates_with_directory(tmpdir):
Use tmp_path please.

2023-06-03 09:02 UTC, Kludex commented on tests/test_templates.py
> +def test_templates_with_directory(tmpdir):
ah, this whole file uses tmpdir, nvm then

2023-06-03 09:22 UTC, Kludex commented
I've rebased it.

2023-06-05 16:34 UTC, alex-oleshkevich commented
I had to make all other arguments as kw-only to make overloading work.

2023-06-05 17:29 UTC, Kludex approved these changes
Thanks 👍 

Let's accept the `context_processors` being a kw-only as a breaking change.

2023-06-05 17:29 UTC, Kludex commented on docs/templates.md
> +Starlette also accepts a preconfigured `jinja2.Environment` instance.
Should we link the `jinja2.Environment` documentation, or no need?

2023-06-05 18:04 UTC, Kludex commented on docs/templates.md
> +Starlette also accepts a preconfigured [`jinja2.Environment`](https://jinja.palletsprojects.com/en/3.0.x/api/#api) instance.
I think this doesn't render very well on mkdocs

2023-06-05 18:17 UTC, alex-oleshkevich commented on docs/templates.md
> +Starlette also accepts a preconfigured [`jinja2.Environment`](https://jinja.palletsprojects.com/en/3.0.x/api/#api) instance.
it looks good
![image](https://github.com/encode/starlette/assets/635848/f9e56d9a-d71f-4c16-9138-dd2db395949b)

2023-06-05 18:19 UTC, Kludex commented on docs/templates.md
> +Starlette also accepts a preconfigured [`jinja2.Environment`](https://jinja.palletsprojects.com/en/3.0.x/api/#api) instance.
Ah ok. Great 👍

2023-06-05 18:19 UTC, Kludex commented
Thanks 👍

2023-06-05 18:20 UTC, merged