Remove flags
Kludex/starlette pull request #2497
Opened 2024-02-09 15:57 UTC by TechNiick

# Summary

This PR is related to [this](https://github.com/encode/starlette/pull/2445) issue. 
This is the final PR, deleted the flags.
# Checklist

- [ ] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [ ] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [ ] I've updated the documentation accordingly.

2024-02-09 16:30 UTC, Kludex commented on scripts/check
>  # github.com/python/mypy/issues/10045. Check github.com/encode/starlette/pull/2180 for more info.
This can be removed, and the part on the pyproject that is commented as well.

2024-02-09 19:55 UTC, Kludex requested changes

2024-02-09 19:55 UTC, Kludex commented on pyproject.toml
> + [[tool.mypy.overrides]]
You can delete those.

2024-02-09 21:38 UTC, Kludex commented
Thanks for your work on all the test files @TechNiick 🙏

2024-02-09 21:38 UTC, Kludex approved these changes

2024-02-09 21:39 UTC, merged

2024-02-10 10:31 UTC, TechNiick commented
> Thanks for your work on all the test files @TechNiick 🙏



> Thanks for your work on all the test files @TechNiick 🙏

Thank you for guidance!