feat: add partiioned attribute to cookie
Kludex/starlette pull request #2501
Opened 2024-02-10 13:34 UTC by Flecart

# Summary

Added the `partitioned` attribute.

See https://github.com/encode/starlette/discussions/2500.

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.

2024-02-15 14:21 UTC, Kludex commented
Closing this since `SimpleCookie` doesn't support it. When that is supported, PR welcome.

2024-02-19 09:38 UTC, Flecart commented
@Kludex can we keep this open as draft like https://github.com/python/cpython/pull/112714 in the meantime?

2024-02-19 10:04 UTC, Kludex commented
I prefer to keep it closed for organization. When that is merged, we can continue the work here.

2025-04-09 11:57 UTC, estyrke commented
The CPython PR is merged now (targeted at 3.14 as far as I can tell). Can this be reopened or do we need a new PR?

2025-04-09 12:01 UTC, Flecart commented
> The CPython PR is merged now (targeted at 3.14 as far as I can tell). Can this be reopened or do we need a new PR?

I'd be happy if this is reopened :)

2025-04-17 00:27 UTC, aaronted009 commented
> > The CPython PR is merged now (targeted at 3.14 as far as I can tell). Can this be reopened or do we need a new PR?
> 
> I'd be happy if this is reopened :)

@Flecart , wish granted 😅 . I guess conflicts could be resolved here so this can move forward?

2025-04-17 14:51 UTC, Flecart commented
> > > The CPython PR is merged now (targeted at 3.14 as far as I can tell). Can this be reopened or do we need a new PR?
> > 
> > 
> > I'd be happy if this is reopened :)
> 
> @Flecart , wish granted 😅 . I guess conflicts could be resolved here so this can move forward?

Sry for the delay, coming!

2025-04-17 15:30 UTC, Flecart commented
Hello people, 
I added the change for partitioned cookies.

This is a **breaking change**, I currently do not know a cleaner version other than checking the version we are in currently, if you have better ways, that'll be well accepted.

Ifrunning set cookie for python version earlier than 3.14 just returns an error like:

```python
    def __setitem__(self, K, V):
        K = K.lower()
        if not K in self._reserved:
>           raise CookieError("Invalid attribute %r" % (K,))
E           http.cookies.CookieError: Invalid attribute 'partitioned'
```

I have tested locally with python version 3.14.0a7.

2025-04-17 16:57 UTC, Kludex commented on starlette/responses.py
> +            cookie[key]["partitioned"] = True  # pragma: no cover
We want an error if `partitioned` is used on <3.14.

2025-04-17 17:26 UTC, Flecart commented on starlette/responses.py
> +            cookie[key]["partitioned"] = True  # pragma: no cover
Can you help me point what line is not coveredby the tests?

2025-04-18 08:32 UTC, Flecart commented
Hello people.
I have added no cover for the whole test that checks for raising errors. I've looked up that in theory we should separate which tests are run for each version and then combine the coverage reports, but this is not compatible with the current testing format. The easiest solution I got was just to ignore coverage so that it works for all versions. Better ideas are welcome.

2025-04-26 15:05 UTC, Flecart commented
@Kludex reminder to check this when you have time. Thank you very much!

2025-05-02 13:13 UTC, Kludex approved these changes

2025-05-02 13:13 UTC, Kludex requested changes

2025-05-02 13:13 UTC, Kludex commented on docs/responses.md
> +* `partitioned` - A bool indicates to user agents that these cross-site cookies should only be available in the same top-level context that the cookie was first set in. `Optional`
We should mention that it's only available on Python 3.14+.

2025-05-04 09:51 UTC, Kludex approved these changes

2025-05-04 09:54 UTC, merged