Add tests to `test_datastructure`
Kludex/starlette pull request #2505
Opened 2024-02-11 16:34 UTC by TechNiick

# Summary

Add test cases to `test_datastructures.py` in order to have 100 coverage. Related to [this issue](https://github.com/encode/starlette/issues/2452) and [this PR](https://github.com/encode/starlette/pull/2503).

# Checklist

- [ ] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [ ] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [ ] I've updated the documentation accordingly.

2024-02-12 08:04 UTC, Kludex requested changes

2024-02-12 08:04 UTC, Kludex commented on tests/test_datastructures.py
> +    assert url.replace(username="user").password is None
What are you testing here?

2024-02-12 08:04 UTC, Kludex commented on tests/test_datastructures.py
> +    assert str(u) == "https://example.org/path/"
What are you testing here?

Better to post the lines you are testing, otherwise, this will take some time for me.

2024-02-26 19:18 UTC, TechNiick commented
This test: 

https://github.com/encode/starlette/blob/4dcdbc4a347a0613a92f5030273eab64381769b5/tests/test_datastructures.py#L61-L62 
Is used for testing the following lines:

https://github.com/encode/starlette/blob/74ccb961b3c1b1871aa7ed70a81dd3000e0194da/starlette/datastructures.py#L134-L136

2024-02-26 19:20 UTC, TechNiick commented
This test: 

https://github.com/encode/starlette/blob/4dcdbc4a347a0613a92f5030273eab64381769b5/tests/test_datastructures.py#L76-L79
Is used for testing the following lines:

https://github.com/encode/starlette/blob/74ccb961b3c1b1871aa7ed70a81dd3000e0194da/starlette/datastructures.py#L154-L156

2024-02-26 19:21 UTC, TechNiick commented
This test: 

https://github.com/encode/starlette/blob/4dcdbc4a347a0613a92f5030273eab64381769b5/tests/test_datastructures.py#L148-L160
Is used for testing the following lines:

https://github.com/encode/starlette/blob/74ccb961b3c1b1871aa7ed70a81dd3000e0194da/starlette/datastructures.py#L39-L40

2024-02-29 10:08 UTC, Kludex commented on tests/test_datastructures.py
> +
I meant doing it here... 
https://github.com/encode/starlette/blob/74ccb961b3c1b1871aa7ed70a81dd3000e0194da/starlette/datastructures.py#L39-L40

2024-03-24 17:18 UTC, Kludex approved these changes
Thanks! 👍 

I've updated the test cases to match the current pattern we have there.

2024-03-24 17:19 UTC, merged