test: refine the test of client disconnection after reading request body
Kludex/starlette pull request #2639
Opened 2024-07-09 19:23 UTC by iamgodot

# Summary

The test's original name and doc aren't really describing what it does so I refined it.

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.

2024-07-09 23:26 UTC, iamgodot commented
@aminalaee @Kludex Appreciate if u can take a look sometime 🙏

2024-07-10 06:59 UTC, Kludex requested changes

2024-07-10 06:59 UTC, Kludex commented on tests/test_requests.py
> -def test_request_is_disconnected(test_client_factory: TestClientFactory) -> None:
The name of the test reflects that we are testing `request.is_disconnected()`.

2024-07-10 06:59 UTC, Kludex commented on tests/test_requests.py
> +    then ClientDisconnect should not be raised.
This makes sense to change, I think it was copy-paste from the above tests.

2024-07-10 06:59 UTC, Kludex commented on tests/test_requests.py
> +    then ClientDisconnect should not be raised.
I think we can improve it tho, because it doesn't make sense to say what would not happen, we should explain what will happen succinctly.

2024-07-10 18:15 UTC, iamgodot commented on tests/test_requests.py
> -def test_request_is_disconnected(test_client_factory: TestClientFactory) -> None:
Alright, I'll keep it as before

2024-07-10 18:15 UTC, iamgodot commented on tests/test_requests.py
> +    then ClientDisconnect should not be raised.
Got ur point, I'll update

2024-07-11 18:22 UTC, iamgodot commented
@Kludex Hi i've updated the changes, let me know if anything else, thanks

2024-07-20 09:04 UTC, Kludex approved these changes

2024-07-20 09:06 UTC, merged