feat: Optional max_file_size for parsing form files
Kludex/starlette pull request #2718
Opened 2024-10-06 04:12 UTC by khadrawy

# Summary

Limiting the size of file being uploaded in case the storage is limited or some business logic can't handle certain size.

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.

2024-12-03 07:44 UTC, Kludex commented
If we instead make the `max_part_size` configurable, would that already be good enough here?

2024-12-03 10:44 UTC, khadrawy commented
> If we instead make the `max_part_size` configurable, would that already be good enough here?

But from what I see [here](https://github.com/encode/starlette/blob/master/starlette/formparsers.py#L157) is that this is only applied to non file parts.

2024-12-03 11:01 UTC, Kludex commented
> > If we instead make the `max_part_size` configurable, would that already be good enough here?
> 
> But from what I see [here](https://github.com/encode/starlette/blob/master/starlette/formparsers.py?rgh-link-date=2024-12-03T10%3A44%3A28Z#L157) is that this is only applied to non file parts.

Hmmm... Does it make sense to be only on non file parts tho? 🤔

2024-12-03 11:09 UTC, khadrawy commented
@Kludex I think we need different limits for parts vs files. As files are spooled, we could allow larger size but for parts we want to have a stricter limit as it is stored in memory.
I can re-work the PR to make it configurable for both.

2024-12-15 07:08 UTC, khadrawy commented
@Kludex what do you think about making all of limits configurable? https://github.com/encode/starlette/pull/2798/files
I see that you are going to rename the max_file_size here https://github.com/encode/starlette/pull/2780 I can adjust naming if we can go forward with making all of the size limits configurable.

2025-02-22 13:18 UTC, Kludex commented
We can make the limits configurable. We just need to adjust the naming, yep.

Let's start by making the `spool` one configurable, and then we add 1 by one. 🙏 

Can you help?

2025-02-23 15:21 UTC, Kludex requested changes

2025-02-23 15:21 UTC, Kludex commented on starlette/requests.py
> +        max_file_spool_size: int = 1024 * 1024,
```suggestion
        max_spool_size: int = 1024 * 1024,
```

2026-03-23 10:50 UTC, closed without merging