Add content_type attribute to UploadFile
Kludex/starlette pull request #371
Opened 2019-01-31 05:58 UTC by roy-freee

Thanks for your awesome project!

I want to look "Content-Type" header in multipart form request in some cases.

* Add `content_type` to UploadFile class
* If no content_type found, `UloadFile.content_type == None`

ref: https://tools.ietf.org/html/rfc7578#section-4.4

I don't know it's good to be `None` as the default behavior. For example, [Flask's `FileStorage.mimetype`returns empty string as default](https://github.com/pallets/werkzeug/blob/c8144ed2bcab242c80b9c5bbfe0a6f2124af0315/werkzeug/http.py#L371), but [`FileStorage.content_type` returns `None` as default](https://github.com/pallets/werkzeug/blob/c8144ed2bcab242c80b9c5bbfe0a6f2124af0315/werkzeug/datastructures.py#L2704).

2019-01-31 09:23 UTC, lovelydinosaur requested changes
I like this, yes!
Let's change the default to empty string, rather than `None`. After that I think it'll be good to go.

Nice work. 😄

2019-01-31 09:23 UTC, tomchristie commented on starlette/datastructures.py
> +        self, filename: str, content_type: str, file: typing.IO = None
Let's have `content_type` as the last parameter here, and have it default to `""`.

2019-01-31 09:23 UTC, tomchristie commented on starlette/formparsers.py
> +                    content_type = headers.get("Content-Type")
Let's use `headers.get("Content-Type", "")`

2019-02-01 01:21 UTC, roy-freee commented
@tomchristie Done 😃

2019-02-01 08:51 UTC, lovelydinosaur approved these changes

2019-02-01 09:06 UTC, tomchristie commented
Ace!

2019-02-01 09:06 UTC, merged