Fix URL.replace when port  is not provided
Kludex/starlette pull request #381
Opened 2019-02-10 19:10 UTC by taoufik07

When the port is not provided in the `URL.replace`, it uses None.
ref https://github.com/kennethreitz/responder/issues/284

2019-02-10 19:13 UTC, taoufik07 commented
My bad, forgot the tests !!

2019-02-11 02:13 UTC, em92 commented
And you left `print`

2019-02-11 08:06 UTC, em92 commented
Btw, to fix bug in responder it is required to unrestrict 0.10.x version in responder. Or also apply patch to 0.9.x
https://github.com/kennethreitz/responder/blob/69eb843604c43b85ca796721f40c3547fa5bf424/setup.py#L25

2019-02-11 08:36 UTC, taoufik07 commented
I'm aware of that and I think responder should update to .10, but it's up to @kennethreitz

2019-02-11 08:57 UTC, tomchristie commented
It's unclear to me what this fixes.
Want to add a test case so that's more clear?
Ideally if you could also aim for a more minimal diff, that doesn't change the structure around so much - that'd also make it easier to clearly review.

2019-02-11 08:58 UTC, lovelydinosaur requested changes
Thanks! Needs a test case to make it obvious what behavioral change is intended here. Ideally a more minimal diff, too.

2019-02-11 09:09 UTC, tomchristie commented
> I'm aware of that and I think responder should update to .10, but it's up to @kennethreitz

I'd suggest just be proactive and issue the PR on responder making the version update.

2019-02-11 09:33 UTC, taoufik07 commented
> I'd suggest just be proactive and issue the PR on responder making the version update.

Once we fix this issue, I will PR

2019-02-11 09:42 UTC, taoufik07 commented
Sorry, we only need to pass `url.netloc` in https middleware instead of `url.hostname`.
https://github.com/encode/starlette/blob/208b4aa2078a0f58289ffdd9a6100f80ba7ffaf6/starlette/middleware/httpsredirect.py#L14

And I was saying to my self why yesterday I wanted to update the https middleware, now I remember xD.

2019-02-11 09:49 UTC, tomchristie commented
> Sorry, we only need to pass `url.netloc` in https middleware instead of `url.hostname`.

I think the most robust behavior would be to use `url.hostname` if the port is `None`, `80`, or `443`, and `url.netloc` if there's an explicit non-standard port.

*Aside*: Even so - it's not definitive that this is *neccessarily* related to the reported issue on responder.

2019-02-11 09:51 UTC, tomchristie commented
What do you think to this?...

```python
    def __call__(self, scope: Scope) -> ASGIInstance:
        if scope["type"] in ("http", "websocket") and scope["scheme"] in ("http", "ws"):
            redirect_scheme = {"http": "https", "ws": "wss"}[scope["scheme"]]
            netloc = url.hostname if url.port in (None, 80, 443) else url.netloc
            url = URL(scope=scope)
            url = url.replace(scheme=redirect_scheme, netloc=netloc)
            return RedirectResponse(url, status_code=301)
```

2019-02-11 09:59 UTC, taoufik07 commented
looks great

2019-02-11 10:02 UTC, taoufik07 commented
but aren't netloc and hostname gonna be the same if the port in (None, 80, 443) ?

2019-02-11 10:47 UTC, tomchristie commented
Superseeded by #382 
Released as 0.10.2

2019-02-11 10:47 UTC, closed without merging

2019-02-11 10:58 UTC, tomchristie commented
Still not obvious that this is neccessarily related to the issue as raised on responder, tho.

2019-02-11 11:04 UTC, taoufik07 commented
when `localhost:5042` is redirected by the HTTPSMiddleware it uses url.hostname `localhost` and with this fix it now uses the netloc if the port is not standard

2019-02-11 11:32 UTC, em92 commented
> Released as 0.10.2

Version bump commit not in master branch. https://github.com/encode/starlette/blob/master/starlette/__init__.py

2019-02-11 12:15 UTC, tomchristie commented
@em92 Thanks. Resolved.