Add WebSocketException and support for WS handlers
Kludex/starlette pull request #527
Opened 2019-05-24 11:24 UTC by tiangolo

Add WebSocketException and support for WS handlers.

Currently, if an exception is raised inside of a WebSocket endpoint, it bubbles, until a `500` HTTP error is thrown.

This PR implements support for raising and handling exceptions inside of WebSocket endpoints.

It has default handlers using WebSocket codes from the specification.

It includes a generic `WebSocketException` comparable to `HTTPException`.

This would allow raising inside WebSocket endpoints, sub-functions, etc. And handling those errors in a custom manner. It might be used to, e.g. log WebSocket errors, customize a WebSocket closing code, etc.

Related issues: https://github.com/encode/starlette/issues/483, https://github.com/encode/starlette/issues/494

---

In FastAPI, this would allow using dependencies that can raise early in WebSocket routes (e.g. if the correct headers are not present) and other scenarios.

2019-05-24 11:57 UTC, tomchristie commented
Ah cool - interesting yup!

One thing for us to think about - are there currently any codepaths we're not thinking of where we're raising HTTPExceptions in a websocket context? Eg. Routing? Middleware?

2019-05-24 13:18 UTC, tiangolo commented
I just checked all the uses of `HTTPException` and nope, at every point that it is raised it is exclusively for HTTP (e.g. inside of `Route`) or the scope is checked and the `WebSocket` is closed manually before (instead of) raising the `HTTPException`.

---

Nevertheless, I guess it's possible that in some scenarios people get confused and end up using `HTTPExceptions` in WebSocket routes.

I could update the default `HTTPException` handler to check if it's receiving a `Request` or a `WebSocket` and close the WebSocket in that case. What do you think?

2019-11-07 11:11 UTC, chbndrhnns commented
Is there anything that prevents this PR from being merged?

2019-11-07 12:04 UTC, lovelydinosaur requested changes
Great stuff here - thanks!

I think my take here would be:

* Let's defo include the `WebSocketException` handling. That's an obviously great addition.
* Let's defo ensure that uvicorn issues 1011 websocket closes if it gets an exception during the websocket task and the connection is open. It needs to function gracefully in that case whatever. (There's an equivelent plain text 500 page for the http exception case.)
* There's more complicated things to consider wrt. the websocket error handling. Perhaps let's remove that from this PR for now, so that we can discuss it in isolation from the handled-exceptions, which is far clearer.

2019-11-07 12:04 UTC, tomchristie commented on starlette/middleware/errors.py
> +                await websocket.close(code=status.WS_1011_INTERNAL_ERROR)
It's also not really clear if we want/need this *in any case* - In the HTTP case, we can use the handler to issue an application-custom 500 page. In the websocket case there's really nothing available for us to do other than close the the connection, which the server *ought to take care of anyways*.

2019-11-07 12:11 UTC, tomchristie commented
Related, this PR makes me notice that we *could* choose to alter our error handling, so that we *always* run the http error handler (even if a response has already been started), it's just that we *only* return that response if one has not already been started.

```python
if scope["type"] == "http":
    request = Request(scope)
    if self.debug:
        # In debug mode, return traceback responses.
        response = self.debug_response(request, exc)
    elif self.handler is None:
        # Use our default 500 error handler.
        response = self.error_response(request, exc)
    else:
        # Use an installed 500 error handler.
        if asyncio.iscoroutinefunction(self.handler):
            response = await self.handler(request, exc)
        else:
            response = await run_in_threadpool(self.handler, request, exc)

    if not response_started:
        await response(scope, receive, send)
```

2019-12-24 03:18 UTC, luckydonald commented
Hey guys. How's the status on this?

2020-01-05 16:55 UTC, Catastropha commented
any good news?

2020-01-22 22:43 UTC, jkamdjou commented
Would also love to see this merged.

2020-02-12 00:18 UTC, Catastropha commented
Please merge, makes the code more beautiful

2020-02-12 07:50 UTC, tiangolo commented
I have to implement the code review, and that probably includes a PR to Uvicorn that I have to do carefully, I just haven't had time yet. But that's the reason. Hopefully I'll finish it soon.

2021-01-11 17:08 UTC, remi-debette commented
Hi! Is there any news on this?

2021-07-17 21:12 UTC, lewoudar commented
another ping to know it this pull request is still relevant

2021-12-06 09:57 UTC, zljubisic commented
Is there any news?

2021-12-06 10:04 UTC, Kludex commented
Yeah, I talked to @tiangolo about taking the lead on this. I've rebased on #1263. Now I need to work on the uvicorn side.

There's no ETA for this. If someone wants this, implementing the uvicorn part is welcome (info about it on this PR).

2022-02-01 15:59 UTC, Kludex commented
I'm closing this in favor of #1263.

2022-02-01 15:59 UTC, closed without merging

2022-10-03 06:46 UTC, urbanonymous commented
Docs related to https://fastapi.tiangolo.com/advanced/websockets/ should be updated.

`In the future, there will be a WebSocketException that you will be able to raise from anywhere, and add exception handlers for it. It depends on the [PR #527](https://github.com/encode/starlette/pull/527) in Starlette.`